version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: poppop-mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: "poppop"
      MYSQL_USER: ${MYSQLDB_USERNAME}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
      TZ: "Asia/Seoul"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: