# 추가 예시(필요에 따라 사용)
server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: PopPop

#  data:
#    redis:
#      host: localhost
#      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/poppop
    username: ${MYSQLDB_USERNAME}
    password: ${MYSQLDB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

#  security:
#    oauth2:
#      client:
#        registration:
#          kakao:
#            client-id: ${KAKAO_OAUTH_CLIENT_ID}
#            client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            redirect-uri: https://boheommong.site/login/oauth2/code/kakao
#            client-authentication-method: client_secret_post
#            scope:
#              - profile_nickname
#              - account_email
#        provider:
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: id
#
#jwt:
#  secret-key: ${JWT_SECRET_KEY_CODE}
#  issuer: ${JWT_ISSUER}
